#!/usr/bin/env bash
set -e
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
	CREATE ROLE nuxeo PASSWORD '****' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;
	CREATE DATABASE nuxeo ENCODING 'UTF8' OWNER nuxeo;
	GRANT ALL PRIVILEGES ON DATABASE nuxeo TO nuxeo;
EOSQL
