{
 "title": "OS Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Load 1min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.system.load.load1, 1)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Non idle CPU",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(offset(scale(servers.*.system.cpu.idle, -1), 100), 1)"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aggregateWithWildcards(servers.*.disk_util.*.utilization, 'max', 3), 1)"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.system.ram.used, 1)"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk_space._ssd.used, 1)"
    }
   ]
  },
  {
   "title": "Disk available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk_space._ssd.avail, 1)"
    }
   ]
  },
  {
   "title": "Memory buff/cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aggregateWithWildcards(servers.*.system.ram.{cached,buffers}, 'sum', 4), 1)"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.system.ram.free, 1)"
    }
   ]
  }
 ]
}